### 데이터 불러오기

In [1]:
# pymysql import 
import pymysql

In [3]:
# mysql 연결
conn = pymysql.connect(host = '', # DB IP (local에 접속하는 경우 : localhost)
                     port = 3306, # 포트 번호
                     user = '',
                     passwd = '', # mySQL 접속 계정 패스워드
                     db = 'movie', # 데이터베이스명
                     charset='utf8') # 한글 깨짐 방지

In [4]:
# DB 조회 결과를 dictionary로 저장
curs = conn.cursor(pymysql.cursors.DictCursor)

In [5]:
# movie 데이터 조회
sql = '''
SELECT * FROM movie
''' 
curs.execute(sql)

600

In [6]:
# 데이터 조회 결과를 result에 저장
result = curs.fetchall()
    
print(result[0])

{'title': '              개를 훔치는 완벽한 방법', 'distributor': '리틀빅픽처스', 'genre': '드라마', 'release_time': datetime.date(2014, 12, 31), 'time': 109, 'screening_rat': '전체 관람가', 'director': '김성호', 'dir_prev_bfnum': 495535.0, 'dir_prev_num': 1, 'num_staff': 292, 'num_actor': 8, 'box_off_num': 306642}

In [7]:
# pandas 라이브러리 import
import pandas as pd

In [8]:
# 데이터 프레임으로 result 결과 저장
df = pd.DataFrame(result)
print(df.columns) # columns
print(df.head())

Index(['box_off_num', 'dir_prev_bfnum', 'dir_prev_num', 'director',
       'distributor', 'genre', 'num_actor', 'num_staff', 'release_time',
       'screening_rat', 'time', 'title'],
      dtype='object')
   box_off_num  dir_prev_bfnum  dir_prev_num director      distributor genre  \
0       306642        495535.0             1      김성호           리틀빅픽처스   드라마
1         4778             NaN             0      정성복  유니버설픽쳐스인터내셔널코리아   뮤지컬
2         1124         35348.0             1      한윤선              어뮤즈   느와르
3         3404             NaN             0      김태곤            인디스토리   드라마
4      2963652       2636380.0             1      조근현            인벤트 디    액션

   num_actor  num_staff release_time screening_rat  time  \
0          8        292   2014-12-31        전체 관람가   109
1          5          3   2014-09-18        전체 관람가   129
2          3        126   2014-08-14      청소년 관람불가   104
3          4         32   2013-02-21       15세 관람가    85
4          3        365   2012-11-29       15세 관람가   135

                         title
0                개를 훔치는 완벽한 방법
1              1789, 바스티유의 연인들
2              18: 우리들의 성장 느와르
3                     1999, 면회
4                          26년

In [9]:
# 상위 3개의 행만 조회
df.head(3)

,box_off_num,dir_prev_bfnum,dir_prev_num,director,distributor,genre,num_actor,num_staff,release_time,screening_rat,time,title
0,306642,495535.0,1,김성호,리틀빅픽처스,드라마,8,292,2014-12-31,전체 관람가,109,개를 훔치는 완벽한 방법
1,4778,NaN,0,정성복,유니버설픽쳐스인터내셔널코리아,뮤지컬,5,3,2014-09-18,전체 관람가,129,"1789, 바스티유의 연인들"
2,1124,35348.0,1,한윤선,어뮤즈,느와르,3,126,2014-08-14,청소년 관람불가,104,18: 우리들의 성장 느와르

In [10]:
# 데이터프레임 역순으로 뒤집기
df.loc[:,::-1].head(3)

,title,time,screening_rat,release_time,num_staff,num_actor,genre,distributor,director,dir_prev_num,dir_prev_bfnum,box_off_num
0,개를 훔치는 완벽한 방법,109,전체 관람가,2014-12-31,292,8,드라마,리틀빅픽처스,김성호,1,495535.0,306642
1,"1789, 바스티유의 연인들",129,전체 관람가,2014-09-18,3,5,뮤지컬,유니버설픽쳐스인터내셔널코리아,정성복,0,NaN,4778
2,18: 우리들의 성장 느와르,104,청소년 관람불가,2014-08-14,126,3,느와르,어뮤즈,한윤선,1,35348.0,1124

In [11]:
# 역순으로 뒤집어서 새로 저장
df = df.loc[:,::-1]

### 데이터 살펴보기

In [12]:
# 데이터 프레임을 이루고 있는 컬럼명 추출
# 'title', 'time', 'screening_rat', 'release_time', 'num_staff','num_actor', 'genre', 'distributor', 'director', 'dir_prev_num', 'dir_prev_bfnum', 'box_off_num'의 컬럼들을 가지고 있음
df.columns

Index(['title', 'time', 'screening_rat', 'release_time', 'num_staff',
       'num_actor', 'genre', 'distributor', 'director', 'dir_prev_num',
       'dir_prev_bfnum', 'box_off_num'],
      dtype='object')

In [13]:
# 데이터 프레임의 행, 열 크기 확인
# 600개의 행과 12개의 열을 가지고 있음
df.shape

(600, 12)

In [14]:
# 데이터에 대한 전반적인 정보 확인
# 총 컬럼의 수는 600개이며, float 타입 1개, int 타입 5개, object 타입 6개로 구성
# dir_prev_bfnum이 270개로 NaN값이 330개 존재한다는 것을 유추할 수 있음
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 12 columns):
title             600 non-null object
time              600 non-null int64
screening_rat     600 non-null object
release_time      600 non-null object
num_staff         600 non-null int64
num_actor         600 non-null int64
genre             600 non-null object
distributor       600 non-null object
director          600 non-null object
dir_prev_num      600 non-null int64
dir_prev_bfnum    270 non-null float64
box_off_num       600 non-null int64
dtypes: float64(1), int64(5), object(6)
memory usage: 56.3+ KB

### 결측치 처리
- 0으로 대체하기
- 평균으로 대체하기

In [16]:
# 데이터프레임에 null 값이 존재하는지 확인
# dir_prev_bfnum에 Ture = null값이 존재한다는 것을 알 수 있음
pd.isnull(df)

,title,time,screening_rat,release_time,num_staff,num_actor,genre,distributor,director,dir_prev_num,dir_prev_bfnum,box_off_num
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,True,False
9,False,False,False,False,False,False,False,False,False,False,True,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,True,False
13,False,False,False,False,False,False,False,False,False,False,True,False
14,False,False,False,False,False,False,False,False,False,False,True,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,True,False
17,False,False,False,False,False,False,False,False,False,False,True,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,True,False
20,False,False,False,False,False,False,False,False,False,False,True,False
21,False,False,False,False,False,False,False,False,False,False,True,False
22,False,False,False,False,False,False,False,False,False,False,True,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,True,False
25,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
570,False,False,False,False,False,False,False,False,False,False,False,False
571,False,False,False,False,False,False,False,False,False,False,True,False
572,False,False,False,False,False,False,False,False,False,False,True,False
573,False,False,False,False,False,False,False,False,False,False,False,False
574,False,False,False,False,False,False,False,False,False,False,False,False
575,False,False,False,False,False,False,False,False,False,False,False,False
576,False,False,False,False,False,False,False,False,False,False,False,False
577,False,False,False,False,False,False,False,False,False,False,True,False
578,False,False,False,False,False,False,False,False,False,False,True,False
579,False,False,False,False,False,False,False,False,False,False,False,False
580,False,False,False,False,False,False,False,False,False,False,False,False
581,False,False,False,False,False,False,False,False,False,False,False,False
582,False,False,False,False,False,False,False,False,False,False,False,False
583,False,False,False,False,False,False,False,False,False,False,True,False
584,False,False,False,False,False,False,False,False,False,False,True,False
585,False,False,False,False,False,False,False,False,False,False,False,False
586,False,False,False,False,False,False,False,False,False,False,True,False
587,False,False,False,False,False,False,False,False,False,False,False,False
588,False,False,False,False,False,False,False,False,False,False,False,False
589,False,False,False,False,False,False,False,False,False,False,True,False
590,False,False,False,False,False,False,False,False,False,False,True,False
591,False,False,False,False,False,False,False,False,False,False,False,False
592,False,False,False,False,False,False,False,False,False,False,False,False
593,False,False,False,False,False,False,False,False,False,False,True,False
594,False,False,False,False,False,False,False,False,False,False,False,False
595,False,False,False,False,False,False,False,False,False,False,True,False
596,False,False,False,False,False,False,False,False,False,False,True,False
597,False,False,False,False,False,False,False,False,False,False,True,False
598,False,False,False,False,False,False,False,False,False,False,False,False
599,False,False,False,False,False,False,False,False,False,False,False,False

In [18]:
# 데이터프레임 각 컬럼에 null 값이 총 몇개 존재하는지 확인
# dir_prev_bfnum에 330개 존재
df.isnull().sum()

title               0
time                0
screening_rat       0
release_time        0
num_staff           0
num_actor           0
genre               0
distributor         0
director            0
dir_prev_num        0
dir_prev_bfnum    330
box_off_num         0
dtype: int64

In [21]:
# 결측값을 0으로 대체
df_zero = df.fillna(0)

In [22]:
# 하위 3개의 행만 보여줌
df_zero.tail(3)

,title,time,screening_rat,release_time,num_staff,num_actor,genre,distributor,director,dir_prev_num,dir_prev_bfnum,box_off_num
597,흉터,65,15세 관람가,2011-10-13,17,2,드라마,(주)키노아이,임우성,0,0.0,256
598,희망의 별 - 이퀘지레템바,85,전체 관람가,2010-10-07,1,2,다큐멘터리,마운틴 픽처스,이홍석,2,59648.5,1298
599,히말라야,124,12세 관람가,2015-12-16,520,2,드라마,CJ 엔터테인먼트,이석훈,4,3549470.0,7759711

In [25]:
# 결측값을 평균값으로 대체
df_mean = df.fillna(df.mean())

In [28]:
# 상위 3개의 행만 보여줌
df_mean.head(3)

,title,time,screening_rat,release_time,num_staff,num_actor,genre,distributor,director,dir_prev_num,dir_prev_bfnum,box_off_num
0,개를 훔치는 완벽한 방법,109,전체 관람가,2014-12-31,292,8,드라마,리틀빅픽처스,김성호,1,4.955350e+05,306642
1,"1789, 바스티유의 연인들",129,전체 관람가,2014-09-18,3,5,뮤지컬,유니버설픽쳐스인터내셔널코리아,정성복,0,1.050443e+06,4778
2,18: 우리들의 성장 느와르,104,청소년 관람불가,2014-08-14,126,3,느와르,어뮤즈,한윤선,1,3.534800e+04,1124

### 중복값 처리

In [76]:
# drop_duplicates()를 사용해서 중복값 제거
# 아무것도 지정하지 않으면 전체 값을 비교해서 완전히 동일한 경우만 제거
df_zero = df_zero.drop_duplicates()

In [77]:
# 행의 수 변화가 없는 것으로 보아 중복값은 없음
df_zero

,title,time,screening_rat,release_time,num_staff,num_actor,genre,distributor,director,dir_prev_num,dir_prev_bfnum,box_off_num
0,개를 훔치는 완벽한 방법,109,전체 관람가,2014-12-31,292,8,드라마,리틀빅픽처스,김성호,1,495535.000,306642
1,"1789, 바스티유의 연인들",129,전체 관람가,2014-09-18,3,5,뮤지컬,유니버설픽쳐스인터내셔널코리아,정성복,0,0.000,4778
2,18: 우리들의 성장 느와르,104,청소년 관람불가,2014-08-14,126,3,느와르,어뮤즈,한윤선,1,35348.000,1124
3,"1999, 면회",85,15세 관람가,2013-02-21,32,4,드라마,인디스토리,김태곤,0,0.000,3404
4,26년,135,15세 관람가,2012-11-29,365,3,액션,인벤트 디,조근현,1,2636380.000,2963652
5,48미터,97,15세 관람가,2013-07-04,78,4,드라마,CJ 엔터테인먼트,민백두,1,57943.000,13886
6,577 프로젝트,99,15세 관람가,2012-08-30,150,2,코미디,필라멘트 픽쳐스,이근우,2,1198420.000,96080
7,5백만불의 사나이,107,15세 관람가,2012-07-19,157,3,코미디,CJ 엔터테인먼트,김익로,2,107376.000,104736
8,"60년전, 사선에서",63,전체 관람가,2010-06-24,10,0,다큐멘터리,인터콘미디어,박성미,0,0.000,79
9,60만번의 트라이,106,12세 관람가,2014-09-18,37,5,다큐멘터리,인디스토리,박사유,0,0.000,21483
10,7광구,112,15세 관람가,2011-08-04,59,5,SF,CJ E&M 영화부문,김지훈,2,3640580.000,2242510
11,7번방의 선물,127,15세 관람가,2013-01-23,300,8,코미디,(주)NEW,이환경,2,819050.000,12811435
12,7월 32일,96,청소년 관람불가,2010-04-22,10,4,드라마,동국대학교 충무로영상제작센터,진승현,0,0.000,742
13,90분,94,청소년 관람불가,2012-08-23,55,2,공포,사람과 사람들,박선욱,0,0.000,42
14,AV 아이돌,89,청소년 관람불가,2015-07-27,0,4,멜로/로맨스,(주) 케이알씨지,조조 히데오,0,0.000,745
15,Mr.아이돌,114,12세 관람가,2011-11-03,485,3,드라마,시너지,라희찬,3,1648550.000,74261
16,R2B: 리턴투베이스,113,15세 관람가,2012-08-15,477,7,액션,주머니필름,김동원,0,0.000,1201944
17,U.F.O.,91,청소년 관람불가,2012-05-24,70,4,드라마,인디스토리,공귀현,0,0.000,1240
18,가비,115,15세 관람가,2012-03-15,95,4,미스터리,시네마서비스,장윤현,3,627302.000,270602
19,가시,117,청소년 관람불가,2014-04-10,207,2,서스펜스,인벤트 디,김태균,0,0.000,142170
20,가시꽃,103,청소년 관람불가,2013-08-22,21,2,드라마,인디스토리,이돈구,0,0.000,1759
21,"가자, 장미여관으로",85,청소년 관람불가,2014-10-08,26,2,멜로/로맨스,드림로드,김봉은,0,0.000,1533
22,가자! 장미여관으로 2 - 갈증,87,청소년 관람불가,2014-04-10,27,4,멜로/로맨스,에이블엔터테인먼트,김봉은,0,0.000,3534
23,간첩,115,15세 관람가,2012-09-20,372,5,드라마,롯데엔터테인먼트,우민호,1,1012310.000,1310895
24,감금의 시간,91,청소년 관람불가,2015-12-03,1,2,공포,마법사필름,김대성,0,0.000,555
25,감기,121,15세 관람가,2013-08-14,458,3,드라마,(주)아이필름코퍼레이션,김성수,2,72.500,3117859
26,감시자들,119,15세 관람가,2013-07-03,331,3,느와르,(주)NEW,조의석,2,80741.000,5508299
27,강남 1970,135,청소년 관람불가,2015-01-21,719,3,액션,(주)쇼박스,유하,4,1949110.000,2192276
28,강철대오 : 구국의 철가방,113,15세 관람가,2012-10-25,262,4,코미디,롯데엔터테인먼트,육상효,2,837969.000,233211
29,개: dog eat dog,101,청소년 관람불가,2015-03-05,58,5,느와르,어썸 피플,황욱,0,0.000,1504
...,...,...,...,...,...,...,...,...,...,...,...,...
570,한민족 그리고 조선족,61,전체 관람가,2014-12-10,2,6,다큐멘터리,한국YWCA연합회,전화성,3,345.333,71
571,한양 기방 춘향뎐,89,청소년 관람불가,2015-11-25,0,1,멜로/로맨스,(주) 케이알씨지,김민욱,0,0.000,400
572,한여름의 판타지아,97,전체 관람가,2015-06-11,7,3,드라마,인디스토리,장건재,0,0.000,36841
573,함정,96,청소년 관람불가,2015-09-10,156,4,공포,인벤트 디,권형진,1,462623.000,257996
574,해로,113,12세 관람가,2012-03-22,14,2,드라마,(주)키노아이,최종태,1,431231.000,5851
575,해무,111,청소년 관람불가,2014-08-13,510,7,드라마,(주)NEW,심성보,1,3833.000,1475091
576,해적: 바다로 간 산적,130,12세 관람가,2014-08-06,868,2,SF,롯데엔터테인먼트,이석훈,3,1843890.000,8666208
577,행복한 울릉인,76,전체 관람가,2010-02-25,3,2,다큐멘터리,마운틴 픽처스,황석호,0,0.000,1068
578,허삼관,124,12세 관람가,2015-01-14,412,2,드라마,(주)NEW,하정우,0,0.000,956103
579,헤드,100,청소년 관람불가,2011-05-26,290,3,액션,SBS콘텐츠허브,조운,1,145.000,61414
580,헬로우 고스트,111,12세 관람가,2010-12-22,369,6,코미디,NEW,김영탁,3,1877000.000,3019960
581,혈투,111,15세 관람가,2011-02-24,306,3,액션,KT,박훈정,2,2270050.000,43947
582,"협녀, 칼의 기억",121,15세 관람가,2015-08-13,439,3,액션,롯데엔터테인먼트,박흥식,3,120930.000,431310
583,홈 스위트 홈,67,12세 관람가,2014-07-17,8,3,애니메이션,머스트 씨 무비,안도 마사히로,0,0.000,2329
584,홍길동 2084,85,전체 관람가,2011-08-18,2,5,애니메이션,타임스토리그룹,이정인,0,0.000,4586
585,화끈한 써비스: 어느 잔인한 미용사의,72,청소년 관람불가,2015-01-29,80,2,드라마,골든타이드픽처스,남기웅,2,427.000,148
586,화이트: 저주의 멜로디,106,15세 관람가,2011-06-09,98,5,공포,CJ E&M Pictures,김곡,0,0.000,790959
587,화장,94,청소년 관람불가,2015-04-09,309,3,드라마,리틀빅픽쳐스,임권택,1,138190.000,142609
588,화차,117,15세 관람가,2012-03-08,308,3,미스터리,필라멘트 픽쳐스,변영주,2,43734.000,2436884
589,화창한 그날들,90,청소년 관람불가,2014-03-14,12,3,공포,(주)온비즈넷,방현준,0,0.000,310
590,환타스틱 러브짐: 전쟁 같은 사랑,83,청소년 관람불가,2015-10-08,7,7,코미디,(주)유비네트워크,한우진,0,0.000,303
591,황구,87,전체 관람가,2014-10-16,140,3,코미디,골든타이드픽처스,박용집,2,695202.000,72
592,황해,156,청소년 관람불가,2010-12-22,683,3,느와르,(주)쇼박스,나홍진,1,5046100.000,2260512
593,회복,94,12세 관람가,2010-01-14,54,1,다큐멘터리,스토리셋,김종철,0,0.000,155281
594,회사원,96,청소년 관람불가,2012-10-11,342,2,액션,(주)쇼박스,임상윤,3,739522.000,1110523
595,후쿠시마의 미래,70,전체 관람가,2015-04-09,4,1,다큐멘터리,인디플러그,이홍기,0,0.000,938
596,훈장과 악동들,92,전체 관람가,2011-10-27,0,1,다큐멘터리,어뮤즈,김봉곤,0,0.000,39916
597,흉터,65,15세 관람가,2011-10-13,17,2,드라마,(주)키노아이,임우성,0,0.000,256
598,희망의 별 - 이퀘지레템바,85,전체 관람가,2010-10-07,1,2,다큐멘터리,마운틴 픽처스,이홍석,2,59648.500,1298
599,히말라야,124,12세 관람가,2015-12-16,520,2,드라마,CJ 엔터테인먼트,이석훈,4,3549470.000,7759711